import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@/styles/globals.css';
import Navbar from "@/components/Navbar/page";
import Footer from "@/components/Footer/page";
import { ThemeProvider } from "@/components/providers/theme-providers";
import TopLoader from "@/components/providers/top-loader";
import { TailwindIndicator } from "@/components/tailwind-indicator";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <TopLoader />
          <Navbar />
          {children}
          <Footer />
          <TailwindIndicator />
        </ThemeProvider>

      </body>
    </html>
  );
}
